version: '2'

services:
  php:
    build:
      context: ./opt/php
      dockerfile: Dockerfile
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php:/var/log/php
      - ./pro/web:/var/www/html
  #    entrypoint: /tmp/entrypoint.sh

  mysql:
    build:
      context: ./opt/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - ./data/mysql:/var/lib/mysql

  nginx:
    build:
      context: ./opt/nginx
      dockerfile: Dockerfile
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 82:82
      - 83:83
      - 88:88

  memcached:
    build:
      context: ./opt/memcached
      dockerfile: Dockerfile

  redis:
    build:
      context: ./opt/redis
      dockerfile: Dockerfile
    volumes:
      - ./data/redis:/data/db

  mongo:
    build:
      context: ./opt/mongo
      dockerfile: Dockerfile
    volumes:
      - ./data/mongo:/data/db

  phpmyadmin:
    build:
      context: ./tools/phpmyadmin
      dockerfile: Dockerfile
    ports:
      - 81:80
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "123456"